# -*- coding: utf-8 -*-
"""ML_OPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWWuI0RwUEe_nRyklsFdgiCbd43mSPfY
"""

#-------------------------------------------------------------------#
# Importer tous les packages permettant d'utiliser spark et pyspark #
#-------------------------------------------------------------------#

!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop3.2.tgz
!tar xf spark-3.1.1-bin-hadoop3.2.tgz
!pip install -q findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.1-bin-hadoop3.2"

import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

# Importations de quelques fonctions SQL
import pyspark.sql.functions as f
from pyspark.sql.functions import *

#--------#
# Python #
#--------#

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

!pip install h2o

import h2o
from h2o.automl import H2OAutoML

# End

TRAIN = spark.read.csv('/content/sample_data/california_housing_train.csv', header=True, inferSchema=True)
TEST = spark.read.csv('/content/sample_data/california_housing_test.csv', header=True, inferSchema=True)

TRAIN.printSchema()

TRAIN.show(10)

